from __future__ import annotations

from typing import Any, Protocol

from simuloom.runtime.models import RuntimeMapping


class RuntimeStore(Protocol):
    persistent: bool
    storage: str

    def close(self) -> None: ...

    def clear(self) -> None: ...

    def mappings(self, simulation_id: str) -> list[RuntimeMapping]: ...

    def replace_mappings(self, simulation_id: str, mappings: list[RuntimeMapping]) -> None: ...

    def scenario_names(self, simulation_id: str | None = None) -> list[str]: ...

    def scenario_state(self, scenario_name: str) -> str | None: ...

    def ensure_scenario_state(self, simulation_id: str, scenario_name: str, state: str) -> None: ...

    def set_scenario_state(self, scenario_name: str, state: str) -> None: ...

    def append_event(self, simulation_id: str, event: dict[str, Any]) -> None: ...

    def events(self, simulation_id: str | None = None) -> list[dict[str, Any]]: ...

    def clear_events(self, simulation_id: str | None = None) -> None: ...
